name: OWASP ZAP Baseline Scan

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the live site
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'https://code-snippet-manager-atle.vercel.app'
          fail_action: false
          allow_issue_writing: false